// Code generated by protoc-gen-go. DO NOT EDIT.
// source: StockReport.proto

package StockReport

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StockReportRequest struct {
	Resolution           int32    `protobuf:"varint,1,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockReportRequest) Reset()         { *m = StockReportRequest{} }
func (m *StockReportRequest) String() string { return proto.CompactTextString(m) }
func (*StockReportRequest) ProtoMessage()    {}
func (*StockReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_StockReport_14edec0ed5d5fb9f, []int{0}
}
func (m *StockReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockReportRequest.Unmarshal(m, b)
}
func (m *StockReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockReportRequest.Marshal(b, m, deterministic)
}
func (dst *StockReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockReportRequest.Merge(dst, src)
}
func (m *StockReportRequest) XXX_Size() int {
	return xxx_messageInfo_StockReportRequest.Size(m)
}
func (m *StockReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StockReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StockReportRequest proto.InternalMessageInfo

func (m *StockReportRequest) GetResolution() int32 {
	if m != nil {
		return m.Resolution
	}
	return 0
}

func (m *StockReportRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *StockReportRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type StockReportItem struct {
	Stockname            string   `protobuf:"bytes,1,opt,name=stockname,proto3" json:"stockname,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Rating               int32    `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockReportItem) Reset()         { *m = StockReportItem{} }
func (m *StockReportItem) String() string { return proto.CompactTextString(m) }
func (*StockReportItem) ProtoMessage()    {}
func (*StockReportItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_StockReport_14edec0ed5d5fb9f, []int{1}
}
func (m *StockReportItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockReportItem.Unmarshal(m, b)
}
func (m *StockReportItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockReportItem.Marshal(b, m, deterministic)
}
func (dst *StockReportItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockReportItem.Merge(dst, src)
}
func (m *StockReportItem) XXX_Size() int {
	return xxx_messageInfo_StockReportItem.Size(m)
}
func (m *StockReportItem) XXX_DiscardUnknown() {
	xxx_messageInfo_StockReportItem.DiscardUnknown(m)
}

var xxx_messageInfo_StockReportItem proto.InternalMessageInfo

func (m *StockReportItem) GetStockname() string {
	if m != nil {
		return m.Stockname
	}
	return ""
}

func (m *StockReportItem) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *StockReportItem) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

type StockReportResponse struct {
	StockData            []*StockReportItem `protobuf:"bytes,1,rep,name=StockData,proto3" json:"StockData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StockReportResponse) Reset()         { *m = StockReportResponse{} }
func (m *StockReportResponse) String() string { return proto.CompactTextString(m) }
func (*StockReportResponse) ProtoMessage()    {}
func (*StockReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_StockReport_14edec0ed5d5fb9f, []int{2}
}
func (m *StockReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockReportResponse.Unmarshal(m, b)
}
func (m *StockReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockReportResponse.Marshal(b, m, deterministic)
}
func (dst *StockReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockReportResponse.Merge(dst, src)
}
func (m *StockReportResponse) XXX_Size() int {
	return xxx_messageInfo_StockReportResponse.Size(m)
}
func (m *StockReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StockReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StockReportResponse proto.InternalMessageInfo

func (m *StockReportResponse) GetStockData() []*StockReportItem {
	if m != nil {
		return m.StockData
	}
	return nil
}

func init() {
	proto.RegisterType((*StockReportRequest)(nil), "StockReportRequest")
	proto.RegisterType((*StockReportItem)(nil), "StockReportItem")
	proto.RegisterType((*StockReportResponse)(nil), "StockReportResponse")
}

func init() { proto.RegisterFile("StockReport.proto", fileDescriptor_StockReport_14edec0ed5d5fb9f) }

var fileDescriptor_StockReport_14edec0ed5d5fb9f = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xad, 0xcb, 0x16, 0x76, 0x3c, 0x58, 0xa7, 0xa5, 0x2c, 0x22, 0x22, 0x39, 0xf5, 0x94,
	0x43, 0xfd, 0x04, 0x82, 0x22, 0x5e, 0xd3, 0xa3, 0x5e, 0x62, 0x1d, 0x24, 0x68, 0xfe, 0x98, 0x4c,
	0xfd, 0xfc, 0x6e, 0x62, 0x61, 0x63, 0xed, 0x2d, 0xf3, 0x7b, 0xe1, 0xcd, 0x9b, 0x07, 0x17, 0x1b,
	0xf6, 0xdb, 0x0f, 0x45, 0xc1, 0x47, 0x96, 0x21, 0x7a, 0xf6, 0xe2, 0x05, 0xb0, 0x82, 0x8a, 0xbe,
	0x76, 0x94, 0x18, 0xaf, 0x01, 0x22, 0x25, 0xff, 0xb9, 0x63, 0xe3, 0x5d, 0x3f, 0xb9, 0x99, 0xac,
	0x5a, 0x55, 0x11, 0x5c, 0x40, 0x9b, 0x58, 0x47, 0xee, 0x4f, 0x07, 0xa9, 0x51, 0xbf, 0x03, 0xce,
	0xa0, 0x21, 0xf7, 0xd6, 0x37, 0x85, 0xe5, 0xa7, 0x20, 0x38, 0xaf, 0xdc, 0x9f, 0x98, 0x2c, 0x5e,
	0x41, 0x97, 0x32, 0x72, 0xda, 0x52, 0x71, 0xee, 0xd4, 0x08, 0xb2, 0xca, 0xc6, 0x0e, 0x11, 0xb4,
	0x0d, 0x7b, 0xf3, 0x11, 0xe0, 0x12, 0xa6, 0x51, 0xb3, 0x71, 0xef, 0x65, 0x47, 0xab, 0xf6, 0x93,
	0x78, 0x80, 0xf9, 0x9f, 0x23, 0x52, 0xf0, 0x2e, 0x11, 0x4a, 0xe8, 0x0a, 0xbe, 0xd7, 0xac, 0x87,
	0x55, 0xcd, 0xea, 0x6c, 0x3d, 0x93, 0x07, 0x79, 0xd4, 0xf8, 0x65, 0xfd, 0x0c, 0xcb, 0x4a, 0xcd,
	0x68, 0x43, 0xf1, 0xdb, 0x6c, 0x09, 0xef, 0x00, 0x1f, 0x89, 0x0f, 0x44, 0x9c, 0xcb, 0xff, 0xd5,
	0x5d, 0x2e, 0xe4, 0x91, 0x28, 0xe2, 0xe4, 0x75, 0x5a, 0xfa, 0xbe, 0xfd, 0x09, 0x00, 0x00, 0xff,
	0xff, 0xfe, 0x2e, 0x64, 0xd4, 0x84, 0x01, 0x00, 0x00,
}
